# Generated by Django 3.2.1 on 2022-04-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_logo', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=250)),
                ('book_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_logo', models.CharField(max_length=1000)),
                ('recipe_title', models.CharField(max_length=100)),
                ('ingredient_recipe', models.CharField(max_length=250)),
                ('recipe_description', models.CharField(max_length=500)),
                ('is_favorite', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.book')),
            ],
        ),
    ]
